language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

env:
    global:
        - DEPENDS="pytest pytest-cov codecov coverage"
        - OPTIONAL_DEPENDS=""

install:
  - pip install $DEPENDS $OPTIONAL_DEPENDS
  - pip install -e .

matrix:
  include:
    - python: 3.7
    - python: 3.7
      env:
        - DEPENDS="pydicom==0.9.9"
    - python: 3.7
      env:
        - OPTIONAL_DEPENDS="chardet"
    - python: 3.7
      env:
        - OPTIONAL_DEPENDS="chardet"

script:
  - python -m pytest -s --cov=dcmstack

after_success:
  - codecov
